services:
  service1:
    build: ./Service1
    image: juhana/service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
    networks:
      - internal

  service2:
    build: ./Service2
    image: juhana/service2
    expose:
      - "3001"
    networks:
      - internal

networks:
  internal:
    driver: bridge