version: '3'
services:
  nginx:
    build: ./Nginx
    ports:
    - "8197:8197"
    - "8198:8198"
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2
      - redis
    networks:
      - internal
    
  service1-1:
    build: ./Service1
    image: juhana/service1-1
    environment:
      - CONTAINER_NAME=service1-1
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service1-2:
    build: ./Service1
    image: juhana/service1-2
    environment:
      - CONTAINER_NAME=service1-2
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service1-3:
    build: ./Service1
    image: juhana/service1-3
    environment:
      - CONTAINER_NAME=service1-3
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service2:
    build: ./Service2
    image: juhana/service2
    networks:
      - internal

  redis:
    image: redis:latest
    networks:
      - internal

networks:
  internal:
    driver: bridge